export const StaticData = [
  {
    name: "car toys ",
    location: "New York, US",
    rate: 5,
    countRate: 56,
    img: "",
    countJob: "1",
    industry: "Software",
  },
  {
    name: "carols daughter",
    location: "New York, US",
    rate: 3,
    countRate: 56,
    img: "",
    countJob: "2  ",
    industry: "Software",
  },
  {
    name: "baseball savings",
    location: "Chicago, US",
    rate: 2,
    countRate: 56,
    img: "",
    countJob: "3 ",
    industry: "Software",
  },
  {
    name: "ashford",
    location: "Toronto, Italia",
    rate: 4,
    countRate: 56,
    img: "",
    countJob: "4",
    industry: "Software",
  },
  {
    name: "callaway golf",
    location: "San Francisco, US",
    rate: 5,
    countRate: 56,
    img: "",
    countJob: "5 ",
    industry: "Recruiting",
  },
  {
    name: "ibotta, inc",
    location: "New York, US",
    rate: 2,
    countRate: 56,
    img: "",
    countJob: "6 ",
    industry: "Software",
  },
  {
    name: "aceable, inc.",
    location: "New York, US",
    rate: 5,
    countRate: 56,
    img: "",
    countJob: "7 ",
    industry: "Software",
  },
  {
    name: "car toys",
    location: "New York, US",
    rate: 5,
    countRate: 56,
    img: "",
    countJob: "8 ",
    industry: "Advertising",
  },
  {
    name: "carols daughter",
    location: " US ",
    rate: 3,
    countRate: 56,
    img: "",
    countJob: "9 ",
    industry: "Recruiting",
  },
  {
    name: "baseball savings",
    location: "Chicago, US",
    rate: 2,
    countRate: 56,
    img: "",
    countJob: "10 ",
    industry: "Recruiting",
  },
  {
    name: "ashford",
    location: "Toronto, Italia",
    rate: 4,
    countRate: 56,
    img: "",
    countJob: "11 ",
    industry: "Recruiting",
  },
  {
    name: "callaway golf",
    location: "San Francisco, US",
    rate: 5,
    countRate: 56,
    img: "",
    countJob: "12 ",
    industry: "Finance",
  },
  {
    name: "ibotta, inc",
    location: "New York, US",
    rate: 2,
    countRate: 56,
    img: "",
    countJob: "13 ",
    industry: "Finance",
  },
  {
    name: "aceable,inc.",
    location: "New York, US",
    rate: 5,
    countRate: 56,
    img: "",
    countJob: "14 ",
    industry: "Finance",
  },
];
