export const  StaticData =[
    {
        name:"Car Toys ",
        location:"New York, US ",
        rate:5,
        countRate:56,
        img:"",
        countJob:"1",
    },
    {
        name:"Carols Daughter",
        location:" US ",
        rate:3,
        countRate:56,
        img:"",
        countJob:"2  ",
    },
    {
        name:"Baseball Savings",
        location:"Chicago, US ",
        rate:2,
        countRate:56,
        img:"",
        countJob:"3 ",
    },
    {
        name:"Ashford",
        location:"Toronto, Italia",
        rate:4,
        countRate:56,
        img:"",
        countJob:"4 ",
    },
    {
        name:"Callaway Golf",
        location:"San Francisco, US",
        rate:5,
        countRate:56,
        img:"",
        countJob:"5 ",
    },
    {
        name:"Ibotta, Inc",
        location:"New York, US ",
        rate:2,
        countRate:56,
        img:"",
        countJob:"6 ",
    },
    {
        name:"Aceable, Inc.",
        location:"New York, US ",
        rate:5,
        countRate:56,
        img:"",
        countJob:"7 ",
    },
    {
        name:"Car Toys",
        location:"New York, US ",
        rate:5,
        countRate:56,
        img:"",
        countJob:"8 ",
    },
    {
        name:"Carols Daughter",
        location:" US ",
        rate:3,
        countRate:56,
        img:"",
        countJob:"9 ",
    },
    {
        name:"Baseball Savings",
        location:"Chicago, US ",
        rate:2,
        countRate:56,
        img:"",
        countJob:"10 ",
    },
    {
        name:"Ashford",
        location:"Toronto, Italia",
        rate:4,
        countRate:56,
        img:"",
        countJob:"11 ",
    },
    {
        name:"Callaway Golf",
        location:"San Francisco, US",
        rate:5,
        countRate:56,
        img:"",
        countJob:"12 ",
    },
    {
        name:"Ibotta, Inc",
        location:"New York, US ",
        rate:2,
        countRate:56,
        img:"",
        countJob:"13 ",
    },
    {
        name:"Aceable, Inc.",
        location:"New York, US ",
        rate:5,
        countRate:56,
        img:"",
        countJob:"14 ",
    },
   
];